import = [
  "~/.config/alacritty/themes/themes/onedark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
#family = "UbuntuMonoNerdFontMono"
style = "Regular"

[window]
#decorations = "None"
dynamic_padding = false
opacity = 0.98

[window.dimensions]
columns = 70
lines = 15

[window.padding]
x = 10
y = 10

