#! /bin/sh

pkill sxhkd # matar atajas de teclado
sxhkd &     # iniciar atajos de teclado

# picom
pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &

# dunst
pkill dunst
dunst -conf ~/.config/dunst/dunstrc/ &

# polybar
"${HOME}/.config/polybar/launch.sh"
# "${HOME}/polybar-collection/launch.sh"

# feh wallpapers
feh --bg-fill "${HOME}/.wallpapers/Gohan-Beast-00.jpg"

# betterlockscreen and xautolock
pkill xautolock
xautolock -time 5 -locker "betterlockscreen -1" -notify 30 -notifier "notify-send 'Locker' 'Locking screen in 30 seconds'" -killtime 5 -killer "systemctl suspend" &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 5
bspc config window_gap 3

# bspc config top_padding            80
# bspc config bottom_padding         80

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Rofi focus=on
bspc rule -a alacritty desktop='^1'
bspc rule -a google-chrome desktop='^2'

# CUSTOM
bspc config focus_follows_pointer true # siguimiento del rato
# bspc config normal_border_color "#e06c75"
bspc config focused_border_color "#e06c75"
# bspc config presel_feedback_color "#abb2bf"

xsetroot -cursor_name left_ptr & # cambiar cursor

# bordes con picom
picom --experimental-backends &
# bspc config border_width 3
